services:
  redis:
    image: redis
    container_name: redis1
    ports:
      - "6379:6379"
  neo4j:
    image: neo4j
    container_name: neo1
    ports:
      - "7474:7474"  # Puerto para la interfaz web
      - "7687:7687"  # Puerto para el protocolo Bolt
    environment:
      - NEO4J_AUTH=none
  app:
    image: alangodinez/01_neo4j_api
    container_name: alan_neo4j_api
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
      - redis
